server:
  type: simple
  applicationContextPath: /baragon/v2
  connector:
    type: http
    port: 8080

zookeeper:
  quorum: localhost:2181
  zkNamespace: baragon
  sessionTimeoutMillis: 60000
  connectTimeoutMillis: 5000
  retryBaseSleepTimeMilliseconds: 1000
  retryMaxTries: 3